# Generated by Django 2.1 on 2020-02-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picosage', '0003_auto_20200229_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='consumer',
        ),
        migrations.AddField(
            model_name='quote',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='picosage.Property'),
        ),
    ]
